package org.bukkit.potion;

// The API type is generated by dev/gen-potion-effect-type.py from extracted registry data.
// Keep one runtime definition: the generated surface includes the legacy aliases.
