package org.bukkit.event.entity;

/** Enum ABI from Paper ver/26.2, used only to compile binary consumers. */
public class CreatureSpawnEvent {
    public enum SpawnReason {
        NATURAL, JOCKEY,
        @Deprecated(since = "1.14", forRemoval = true) CHUNK_GEN,
        SPAWNER, TRIAL_SPAWNER, EGG, SPAWNER_EGG, LIGHTNING, BUILD_SNOWMAN,
        BUILD_IRONGOLEM, BUILD_COPPERGOLEM, BUILD_WITHER, VILLAGE_DEFENSE,
        VILLAGE_INVASION, BREEDING, SLIME_SPLIT, REINFORCEMENTS, NETHER_PORTAL,
        DISPENSE_EGG, INFECTION, CURED, OCELOT_BABY, SILVERFISH_BLOCK, MOUNT, TRAP,
        ENDER_PEARL, SHOULDER_ENTITY, DROWNED, SHEARED, EXPLOSION, RAID, PATROL,
        BEEHIVE, PIGLIN_ZOMBIFIED, SPELL, FROZEN, METAMORPHOSIS, DUPLICATION,
        COMMAND, ENCHANTMENT, OMINOUS_ITEM_SPAWNER, BUCKET, POTION_EFFECT,
        REANIMATE, REHYDRATION, CUSTOM, DEFAULT
    }
}
