#:schema https://raw.githubusercontent.com/Zeffut/Foton/refs/heads/master/package-content/groups.schema.json
# Documentation: CONFIGURATION.md in the Foton repository

default_groups = ["default"]

[groups.default]
priority = 0
inherits = []
allow = []
deny = []
metadata = []

[groups.op]
priority = 0
inherits = []
allow = ["*"]
deny = []
metadata = []
