name: NoJoinConsumer
version: 1
api-version: '26.2'
main: fixture.dependencies.DependencyPlugins$NoJoinConsumer
dependencies:
  server:
    NoJoinProvider:
      load: BEFORE
      required: true
      join-classpath: false
