edition = "2024"
style_edition = "2024"
newline_style = "Unix"

ignore = [
    "foton-core/src/behavior/generated",
    "foton-core/src/entity/generated",
    "foton-registry/src/generated",
    "foton-utils/src/generated",
    "foton-worldgen/src/generated",
]
