#!/usr/bin/env python3
"""Writes the registry-backed Bukkit values: banner patterns, biomes, trims, goat horns.

Paper turned these from enums into interfaces whose constants are looked up in
a live registry (`PatternType.BASE = getType("base")`). A plugin compiled
against that calls them with `invokeinterface`, so Foton's have to be
interfaces too -- an enum or a class there fails with
IncompatibleClassChangeError the first time it is touched.

The entries come from the vanilla data pack foton-registry itself is built
from (`foton-utils/build_assets/builtin_datapacks`), and their order from the
registration order foton-registry generates, which is the id order Foton sends
to clients. So the Java side cannot name a pattern the server lacks, nor carry
a value -- a trim colour, a horn's range -- that disagrees with it.

Constant names follow Paper's rule, the registry path in upper case.

Two things are written:

- `foton/FotonRegistryData.java`, the entries and their data in registry
  order, as plain arrays that need nothing else to initialise;
- each interface, from `plugin-api/templates/`, with its constants in place of
  the `// @@CONSTANTS@@` line.

    python3 dev/gen-registry-values.py <output-directory>
"""
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DATAPACK = REPO / "foton-utils" / "build_assets" / "builtin_datapacks" / "minecraft"
GENERATED = REPO / "foton-registry" / "src" / "generated"
TEMPLATES = REPO / "plugin-api" / "templates"
MARKER = "    // @@CONSTANTS@@"

# (data pack directory, generated registration file, Java data prefix)
REGISTRIES = {
    "banner_pattern": ("banner_pattern", "vanilla_banner_patterns"),
    "biome": ("worldgen/biome", "vanilla_biomes"),
    "trim_material": ("trim_material", "vanilla_trim_materials"),
    "trim_pattern": ("trim_pattern", "vanilla_trim_patterns"),
    "instrument": ("instrument", "vanilla_instruments"),
}

# (template path, registry, how one constant is declared)
TEMPLATED = [
    ("org/bukkit/block/banner/PatternType.java", "banner_pattern",
     '    PatternType {name} = org.bukkit.Registry.BANNER_PATTERN.getOrThrow(org.bukkit.NamespacedKey.minecraft("{key}"));'),
    ("org/bukkit/block/Biome.java", "biome",
     '    Biome {name} = org.bukkit.Registry.BIOME.getOrThrow(org.bukkit.NamespacedKey.minecraft("{key}"));'),
    ("org/bukkit/inventory/meta/trim/TrimMaterial.java", "trim_material",
     '    TrimMaterial {name} = org.bukkit.Registry.TRIM_MATERIAL.getOrThrow(org.bukkit.NamespacedKey.minecraft("{key}"));'),
    ("org/bukkit/inventory/meta/trim/TrimPattern.java", "trim_pattern",
     '    TrimPattern {name} = org.bukkit.Registry.TRIM_PATTERN.getOrThrow(org.bukkit.NamespacedKey.minecraft("{key}"));'),
    ("org/bukkit/MusicInstrument.java", "instrument",
     '    public static final MusicInstrument {name} = Registry.INSTRUMENT.getOrThrow(NamespacedKey.minecraft("{key}"));'),
]


def registration_order(generated):
    """Entry paths in the order foton-registry registers them."""
    text = (GENERATED / f"{generated}.rs").read_text(encoding="utf-8")
    statics = dict(re.findall(r'pub static ([A-Z][A-Z0-9_]*)\s*:.*?vanilla_static\s*\(\s*"([^"]+)"', text))
    body = re.search(r"pub fn register_\w+\s*\([^)]*\)\s*\{(.*?)\}", text, re.S)
    if not body:
        raise SystemExit(f"no registration function in {generated}.rs; build foton-registry first")
    order = [statics[name] for name in re.findall(r"register\s*\(\s*&\s*\*?\s*([A-Z][A-Z0-9_]*)\s*\)", body.group(1))]
    if not order:
        raise SystemExit(f"no entries registered in {generated}.rs")
    return order


def read(directory, generated):
    entries = []
    for path in registration_order(generated):
        source = DATAPACK / directory / f"{path}.json"
        if not source.is_file():
            raise SystemExit(f"{source} is missing; the data pack and the registry disagree")
        entries.append((path, json.loads(source.read_text(encoding="utf-8"))))
    return entries


def java_string(value):
    return json.dumps(value, ensure_ascii=False)


def java_float(value):
    return f"{float(value)!r}f"


def description(entry):
    """(translation key, colour or null) of a data pack `description` component."""
    component = entry.get("description")
    if isinstance(component, str):
        return component, None
    if not isinstance(component, dict) or "translate" not in component:
        raise SystemExit(f"unsupported description {component!r}")
    return component["translate"], component.get("color")


def array(kind, values):
    return f"new {kind}[] {{" + ", ".join(values) + "}"


def data_class(registries):
    lines = [
        "package foton;",
        "",
        "/** Vanilla registry entries in foton-registry's order. Generated by dev/gen-registry-values.py. */",
        "public final class FotonRegistryData {",
        "    private FotonRegistryData() { }",
    ]
    for registry, entries in registries.items():
        prefix = registry.upper()
        lines.append(f"    public static final String[] {prefix}_KEYS = "
                     + array("String", [java_string(key) for key, _ in entries]) + ";")

    patterns = registries["banner_pattern"]
    lines.append("    public static final String[] BANNER_PATTERN_TRANSLATION_KEYS = "
                 + array("String", [java_string(data["translation_key"]) for _, data in patterns]) + ";")

    for registry in ("trim_material", "trim_pattern", "instrument"):
        entries = registries[registry]
        described = [description(data) for _, data in entries]
        prefix = registry.upper()
        lines.append(f"    public static final String[] {prefix}_DESCRIPTIONS = "
                     + array("String", [java_string(key) for key, _ in described]) + ";")
        lines.append(f"    public static final String[] {prefix}_COLORS = "
                     + array("String", ["null" if color is None else java_string(color) for _, color in described]) + ";")

    materials = registries["trim_material"]
    lines.append("    public static final String[] TRIM_MATERIAL_ASSETS = "
                 + array("String", [java_string(data["asset_name"]) for _, data in materials]) + ";")
    trims = registries["trim_pattern"]
    lines.append("    public static final boolean[] TRIM_PATTERN_DECALS = "
                 + array("boolean", ["true" if data.get("decal") else "false" for _, data in trims]) + ";")

    horns = registries["instrument"]
    lines.append("    public static final String[] INSTRUMENT_SOUNDS = "
                 + array("String", [java_string(data["sound_event"]) for _, data in horns]) + ";")
    lines.append("    public static final float[] INSTRUMENT_DURATIONS = "
                 + array("float", [java_float(data["use_duration"]) for _, data in horns]) + ";")
    lines.append("    public static final float[] INSTRUMENT_RANGES = "
                 + array("float", [java_float(data["range"]) for _, data in horns]) + ";")
    lines.append("    /** Items in minecraft:trimmable_armor, whose meta is ArmorMeta, as Paper gives them. */")
    lines.append("    public static final String[] TRIMMABLE_ARMOR = "
                 + array("String", [java_string(key) for key in item_tag("trimmable_armor")]) + ";")
    lines.append("}")
    return "\n".join(lines) + "\n"


def item_tag(path, including=()):
    """The items of an item tag, following the tags it includes, in data pack order."""
    if path in including:
        raise SystemExit(f"item tag {path} includes itself")
    including = (*including, path)
    source = DATAPACK / "tags" / "item" / f"{path}.json"
    items = []
    for value in json.loads(source.read_text(encoding="utf-8"))["values"]:
        entry = value if isinstance(value, str) else value["id"]
        if entry.startswith("#"):
            items += item_tag(entry[1:].removeprefix("minecraft:"), including)
        else:
            items.append(entry.removeprefix("minecraft:"))
    return list(dict.fromkeys(items))


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: gen-registry-values.py <output-directory>")
    out = pathlib.Path(sys.argv[1])
    registries = {name: read(directory, generated) for name, (directory, generated) in REGISTRIES.items()}

    target = out / "foton" / "FotonRegistryData.java"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(data_class(registries), encoding="utf-8")

    for template, registry, declaration in TEMPLATED:
        text = (TEMPLATES / template).read_text(encoding="utf-8")
        if text.count(MARKER) != 1:
            raise SystemExit(f"{template} needs exactly one {MARKER.strip()} line")
        # Paper lists them alphabetically; the registry keeps its own order.
        keys = sorted(key for key, _ in registries[registry])
        constants = "\n".join(declaration.format(name=key.upper(), key=key) for key in keys)
        target = out / template
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text.replace(MARKER, constants), encoding="utf-8")

    print("generated " + ", ".join(f"{len(entries)} {name}s" for name, entries in registries.items()))


if __name__ == "__main__":
    main()
