#!/usr/bin/env python3
"""Render CONFIGURATION.md from the shipped JSON schemas.

The schemas in `package-content/` are the only description of the config
format that is checked against the code, so the reference is generated from
them rather than transcribed. Run this after changing a schema:

    python3 dev/gen-config-docs.py

`dev/ci.sh` runs this with `--check`, which fails when the committed file no
longer matches what the schemas produce.
"""

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import config_schema as cs

REPO = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = REPO / "CONFIGURATION.md"

FILES = cs.FILES


def type_of(node, root):
    """A short human type for one property, as Markdown."""
    kind, value = cs.type_parts(node, root)
    if kind == "ref":
        return f"[`{value}`](#{value.replace('_', '-')})"
    if kind == "enum":
        return " \\| ".join(f"`{v}`" for v in value)
    if kind == "union":
        return " or ".join(dict.fromkeys(_format_part(p) for p in value))
    if kind == "array":
        return f"array of {_format_part(value)}" if value else "array"
    if kind == "object":
        return "table"
    return value


def _format_part(part):
    kind, value = part
    if kind == "ref":
        return f"[`{value}`](#{value.replace('_', '-')})"
    if kind == "enum":
        return " \\| ".join(f"`{v}`" for v in value)
    if kind == "array":
        return f"array of {_format_part(value)}" if value else "array"
    if kind == "object":
        return "table"
    return value


def cell(text):
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def default_of(node, root):
    value = cs.default_of(node, root)
    if value is None:
        return ""
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, str) and value == "":
        return "`\"\"`"
    return f"`{json.dumps(value)}`"


def table(node, root):
    rows = [
        f"| `{name}`{' *(required)*' if required else ''} | {type_of(prop, root)} "
        f"| {default_of(prop, root)} | {cell(cs.limits(prop, root))} "
        f"| {cell(cs.resolve(prop, root).get('description'))} |"
        for name, prop, required in cs.rows(node, root)
    ]
    if not rows:
        return []
    return ["| Key | Type | Default | Range | Meaning |",
            "|---|---|---|---|---|", *rows, ""]


def section(node, root, title, depth, lines):
    node = cs.resolve(node, root)
    description = node.get("description")
    if description and depth > 3:
        lines.append(f"{description}\n")
    lines.extend(table(node, root))
    for name, prop in cs.subsections(node, root):
        heading = f"{title}.{name}" if title else name
        lines.append(f"{'#' * depth} `[{heading}]`\n")
        section(prop, root, heading, depth + 1, lines)


def render():
    lines = [
        "# Configuration reference",
        "",
        "*Generated by `python3 dev/gen-config-docs.py` from the JSON schemas in",
        "`package-content/`. Edit the schema, not this file.*",
        "",
        "Foton writes its defaults on first boot into `config/` next to the server",
        "binary, then reads them on every later start. Each file carries a `#:schema`",
        "line so an editor with TOML schema support can complete and validate it.",
        "",
    ]
    for toml_name, schema_name, title, blurb in FILES:
        schema = cs.load(schema_name)
        lines += [f"## `{toml_name}` — {title}", "", f"{schema.get('description', blurb)}.", ""]
        body = []
        section(schema, schema, "", 3, body)
        lines += body
        definitions = schema.get("definitions") or {}
        shapes = {k: v for k, v in definitions.items()
                  if (v.get("type") == "object" and v.get("properties"))}
        if shapes:
            lines += [f"### Shapes used by `{toml_name}`", ""]
            for name, node in shapes.items():
                lines += [f"#### `{name}`", ""]
                inner = []
                section(node, schema, name, 5, inner)
                lines += inner
        scalars = {k: v for k, v in definitions.items() if k not in shapes}
        if scalars:
            lines += [f"### Value types used by `{toml_name}`", "",
                      "| Name | Accepts | Meaning |", "|---|---|---|"]
            for name, node in scalars.items():
                accepts = type_of(node, schema)
                if node.get("pattern"):
                    accepts += f" matching `{node['pattern']}`"
                lines.append(f"| <a id=\"{name.replace('_', '-')}\"></a>`{name}` "
                             f"| {accepts} | {cell(node.get('description'))} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(REPO)} is stale; run python3 dev/gen-config-docs.py")
            return 1
        print(f"{OUTPUT.relative_to(REPO)} is current")
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT.relative_to(REPO)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
