package org.bukkit;

/** Legacy world effects understood by Bukkit plugins. */
public enum Effect {
    CLICK1, CLICK2, BOW_FIRE, DOOR_TOGGLE, IRON_DOOR_TOGGLE, TRAPDOOR_TOGGLE,
    IRON_TRAPDOOR_TOGGLE, FENCE_GATE_TOGGLE, EXTINGUISH, RECORD_PLAY, GHAST_SHRIEK,
    GHAST_SHOOT, BLAZE_SHOOT, ZOMBIE_CHEW_WOODEN_DOOR, ZOMBIE_DESTROY_DOOR,
    SMOKE, STEP_SOUND, POTION_BREAK, ENDER_SIGNAL, MOBSPAWNER_FLAMES,
    ANVIL_BREAK, ANVIL_LAND, ANVIL_USE, ENDERDRAGON_SHOOT, WITHER_SHOOT,
    ZOMBIE_INFECT, ZOMBIE_CONVERTED, BAT_TAKEOFF, ENDERDRAGON_GROWL,
    VILLAGER_PLANT_GROW, DRAGON_BREATH, END_PORTAL_FRAME_FILL, ENDER_SIGNAL2,
    ELECTRIC_SPARK, WAX_ON, WAX_OFF, SCRAPE
}
