//! Choosing which configured Foton world receives each source dimension.

use std::path::PathBuf;

use foton_utils::Identifier;

use super::{ImportError, ImportTarget, SourceDimension};
use crate::chunk_saver::registry::WorldStorageRegistry;
use crate::config::{ResolvedWorldConfig, WorldStorageConfig, WorldsConfig};
use crate::worldgen::WorldGeneratorRegistry;

const fn layout_error(message: String) -> ImportError {
    ImportError::Layout(message)
}

/// Resolves the Foton world each dimension is imported into.
///
/// With no `world_override`, a dimension goes to the default domain's world of
/// the same name (`overworld`, `the_nether`, `the_end` in a stock
/// `worlds.toml`), falling back to the world generated by the dimension's own
/// vanilla generator. `world_override` is `world` in the default domain or
/// `domain:world`, and is only meaningful for a single dimension.
///
/// # Errors
/// Returns an error if `worlds.toml` is invalid, no world matches, two
/// dimensions would land in one world, or the world is not stored on disk.
pub fn resolve_targets(
    worlds: &WorldsConfig,
    dimensions: Vec<SourceDimension>,
    world_override: Option<&str>,
) -> Result<Vec<ImportTarget>, ImportError> {
    let generators = WorldGeneratorRegistry::new_with_builtins()
        .map_err(|error| layout_error(format!("world generator registry: {error}")))?;
    let storage = WorldStorageRegistry::new_with_builtins()
        .map_err(|error| layout_error(format!("world storage registry: {error}")))?;
    let resolved = worlds
        .validate_and_resolve(&generators, &storage)
        .map_err(|error| layout_error(format!("worlds.toml: {error}")))?;
    if world_override.is_some() && dimensions.len() != 1 {
        return Err(layout_error(
            "--world names one Foton world, so exactly one --dimension must be given".to_owned(),
        ));
    }

    let mut targets: Vec<ImportTarget> = Vec::with_capacity(dimensions.len());
    for dimension in dimensions {
        let world = find_world(
            &resolved.worlds,
            &resolved.default_domain,
            &dimension,
            world_override,
        )?;
        if targets.iter().any(|target| target.world_key == world.key) {
            return Err(layout_error(format!(
                "two dimensions would both be imported into {}",
                world.key
            )));
        }
        let default_path = resolved
            .save_path
            .join(&world.domain)
            .join("worlds")
            .join(&world.name);
        let output = storage
            .create(&world.storage, &resolved.save_path, &default_path)
            .map_err(|error| layout_error(format!("storage of {}: {error}", world.key)))?;
        let (WorldStorageConfig::Disk { path }, Some(level_dir)) =
            (output.storage, output.level_data_path)
        else {
            return Err(layout_error(format!(
                "{} does not use disk storage, so there is nowhere to import into",
                world.key
            )));
        };
        let is_spawn_world = resolved
            .domains
            .iter()
            .find(|domain| domain.name == resolved.default_domain)
            .is_some_and(|domain| domain.default_world == world.key);
        targets.push(ImportTarget {
            dimension: dimension.key,
            source_dir: dimension.dir,
            world_key: world.key.clone(),
            level_dir,
            region_dir: PathBuf::from(path),
            is_spawn_world,
        });
    }
    Ok(targets)
}

fn find_world<'a>(
    worlds: &'a [ResolvedWorldConfig],
    default_domain: &str,
    dimension: &SourceDimension,
    world_override: Option<&str>,
) -> Result<&'a ResolvedWorldConfig, ImportError> {
    if let Some(wanted) = world_override {
        let (domain, name) = wanted.split_once(':').unwrap_or((default_domain, wanted));
        return worlds
            .iter()
            .find(|world| world.domain == domain && world.name == name)
            .ok_or_else(|| {
                layout_error(format!(
                    "worlds.toml has no world {domain}:{name}; worlds are: {}",
                    world_names(worlds)
                ))
            });
    }
    let by_name = worlds
        .iter()
        .find(|world| world.domain == default_domain && world.name == dimension.key.path);
    let by_generator = || {
        worlds
            .iter()
            .find(|world| world.domain == default_domain && world.generator == dimension.key)
    };
    by_name.or_else(by_generator).ok_or_else(|| {
        layout_error(format!(
            "no world in the default domain `{default_domain}` receives {}; worlds are: {}. \
             Name one with --world",
            dimension.key,
            world_names(worlds)
        ))
    })
}

fn world_names(worlds: &[ResolvedWorldConfig]) -> String {
    worlds
        .iter()
        .map(|world| world.key.to_string())
        .collect::<Vec<_>>()
        .join(", ")
}

/// Resolves a command-line dimension name: a bare vanilla path such as `nether`
/// or `the_nether`, or a full id.
#[must_use]
pub fn parse_dimension_name(name: &str) -> Option<Identifier> {
    let path = match name {
        "nether" => "the_nether",
        "end" => "the_end",
        other => other,
    };
    path.parse().ok()
}
