name: PaperConsumer
version: 1
api-version: '26.2'
main: fixture.dependencies.DependencyPlugins$PaperConsumer
dependencies:
  bootstrap:
    BootstrapProvider:
      load: BEFORE
      required: true
      join-classpath: true
  server:
    ServerAfter:
      load: AFTER
      required: false
      join-classpath: false
