name: AfterConsumer
version: 1
api-version: '26.2'
main: fixture.dependencies.DependencyPlugins$AfterConsumer
dependencies:
  server:
    AfterProvider:
      load: AFTER
      required: true
      join-classpath: true
