package org.bukkit.block;

import org.bukkit.Keyed;
import org.bukkit.NamespacedKey;

/** Vanilla biome key. Values cover the biome names used by the current data pack. */
public enum Biome implements Keyed {
    THE_VOID, PLAINS, SUNFLOWER_PLAINS, SNOWY_PLAINS, ICE_SPIKES, DESERT,
    SWAMP, MANGROVE_SWAMP, FOREST, FLOWER_FOREST, BIRCH_FOREST, DARK_FOREST,
    OLD_GROWTH_BIRCH_FOREST, OLD_GROWTH_PINE_TAIGA, OLD_GROWTH_SPRUCE_TAIGA,
    TAIGA, SNOWY_TAIGA, JUNGLE, SPARSE_JUNGLE, BAMBOO_JUNGLE, SAVANNA,
    SAVANNA_PLATEAU, WINDSWEPT_HILLS, WINDSWEPT_GRAVELLY_HILLS, WINDSWEPT_FOREST,
    WINDSWEPT_SAVANNA, BADLANDS, ERODED_BADLANDS, WOODED_BADLANDS,
    MEADOW, CHERRY_GROVE, GROVE, SNOWY_SLOPES, FROZEN_PEAKS, JAGGED_PEAKS,
    STONY_PEAKS, RIVER, FROZEN_RIVER, BEACH, SNOWY_BEACH, STONY_SHORE,
    OCEAN, DEEP_OCEAN, COLD_OCEAN, DEEP_COLD_OCEAN, FROZEN_OCEAN,
    DEEP_FROZEN_OCEAN, LUKEWARM_OCEAN, DEEP_LUKEWARM_OCEAN, WARM_OCEAN,
    MUSHROOM_FIELDS, DRIPSTONE_CAVES, LUSH_CAVES, DEEP_DARK,
    NETHER_WASTES, SOUL_SAND_VALLEY, CRIMSON_FOREST, WARPED_FOREST,
    BASALT_DELTAS, THE_END, END_HIGHLANDS, END_MIDLANDS, SMALL_END_ISLANDS,
    END_BARRENS, NETHER_SPROUTS, PALE_GARDEN;

    private final NamespacedKey key = NamespacedKey.minecraft(name().toLowerCase(java.util.Locale.ROOT));
    @Override public NamespacedKey getKey() { return key; }
}
