//! Item behavior implementations.
//!
//! The actual behavior registration is auto-generated from classes.json.
//! See `src/behavior/generated/items.rs` for the generated registration code.

mod air;
mod armor_stand_item;
mod arrow;
mod axe;
mod banner_item;
mod bed_item;
mod block_item;
mod boat_item;
mod bonemeal;
mod book;
mod bottle;
mod bow;
mod brush;
mod bucket;
mod bundle;
mod compass;
mod copper_chest_events;
mod crossbow;
mod debug_stick;
mod default;
mod dye;
mod dynamic_name;
mod end_crystal_item;
mod ender_eye;
mod ender_pearl;
mod firework_rocket;
mod fishing_rod;
mod flint_and_steel;
mod food_on_a_stick;
mod game_master_block_item;
mod hanging_entity_item;
mod hoe;
mod honeycomb;
mod ink_sac;
mod instrument;
mod item_frame_item;
mod knowledge_book;
mod lead_item;
mod mace;
pub(crate) mod map_item;
mod minecart_item;
mod mob_bucket;
mod name_tag;
mod place_on_water_block_item;
mod player_head;
mod potion;
mod scaffolding_block_item;
mod shears;
mod shield;
mod shovel;
mod sign_item;
mod solid_bucket;
mod spawn_egg;
mod spyglass;
mod standing_and_wall_block_item;
mod throwable_items;
mod throwable_potion;
mod tipped_arrow;
mod tooltip_only;
mod trident;
mod wind_charge;

pub use air::AirItem;
pub use armor_stand_item::ArmorStandItem;
pub use arrow::{ArrowItem, SpectralArrowItem, arrow_entity_type_for};
pub use axe::AxeItem;
pub use banner_item::BannerItem;
pub use bed_item::BedItem;
pub use block_item::{BlockItem, DoubleHighBlockItem};
pub use boat_item::BoatItem;
pub use bonemeal::BoneMealItem;
pub use book::{WritableBookItem, WrittenBookItem};
pub use bottle::BottleItem;
pub use bow::BowItem;
pub use brush::BrushItem;
pub use bucket::BucketItem;
pub use bundle::{BundleItem, MutableBundleContents, can_item_be_in_bundle};
pub use compass::CompassItem;
pub use crossbow::CrossbowItem;
/// Vanilla parity: `CrossbowItem.getChargeDuration`, which a mob's crossbow
/// goal has to know because it winds the weapon itself.
pub(crate) use crossbow::charge_duration as crossbow_charge_duration;
pub use debug_stick::DebugStickItem;
pub use default::DefaultItemBehavior;
pub use dye::DyeItem;
pub use end_crystal_item::EndCrystalItem;
pub use ender_eye::EnderEyeItem;
pub use ender_pearl::EnderPearlItem;
pub use firework_rocket::FireworkRocketItem;
pub use fishing_rod::FishingRodItem;
pub use flint_and_steel::{FireChargeItem, FlintAndSteelItem};
pub use food_on_a_stick::FoodOnAStickItem;
pub use game_master_block_item::GameMasterBlockItem;
pub use hanging_entity_item::HangingEntityItem;
pub use hoe::HoeItem;
pub use honeycomb::HoneycombItem;
pub use ink_sac::{GlowInkSacItem, InkSacItem};
pub use instrument::InstrumentItem;
pub use item_frame_item::ItemFrameItem;
pub use knowledge_book::KnowledgeBookItem;
pub use lead_item::{LeadItem, bind_player_mobs};
pub use mace::MaceItem;
pub use map_item::{EmptyMapItem, MapItem, saved_data as saved_map_data};
pub use minecart_item::MinecartItem;
pub use mob_bucket::MobBucketItem;
pub use name_tag::NameTagItem;
pub use place_on_water_block_item::PlaceOnWaterBlockItem;
pub use player_head::PlayerHeadItem;
pub use potion::PotionItem;
pub use scaffolding_block_item::ScaffoldingBlockItem;
pub use shears::ShearsItem;
pub use shield::ShieldItem;
pub use shovel::ShovelItem;
pub use sign_item::{HangingSignItem, SignItem};
pub use solid_bucket::SolidBucketItem;
pub use spawn_egg::SpawnEggItem;
pub use spyglass::SpyglassItem;
pub use standing_and_wall_block_item::StandingAndWallBlockItem;
pub use throwable_items::{EggItem, ExperienceBottleItem, SnowballItem};
pub use throwable_potion::{LingeringPotionItem, SplashPotionItem};
pub use tipped_arrow::TippedArrowItem;
pub use tooltip_only::{DiscFragmentItem, SmithingTemplateItem};
pub use trident::TridentItem;
pub use wind_charge::WindChargeItem;
