//! Item behavior implementations.
//!
//! The actual behavior registration is auto-generated from classes.json.
//! See `src/behavior/generated/items.rs` for the generated registration code.

mod air;
mod armor_stand_item;
mod axe;
mod bed_item;
mod block_item;
mod boat_item;
mod bonemeal;
mod bottle;
mod bow;
mod brush;
mod bucket;
mod compass;
mod copper_chest_events;
mod default;
mod dye;
mod dynamic_name;
mod ender_eye;
mod ender_pearl;
mod firework_rocket;
mod food_on_a_stick;
mod hanging_entity_item;
mod hoe;
mod honeycomb;
mod ink_sac;
mod instrument;
mod item_frame_item;
mod lead_item;
mod mace;
mod minecart_item;
mod name_tag;
mod place_on_water_block_item;
mod player_head;
mod potion;
mod shears;
mod shield;
mod shovel;
mod sign_item;
mod spawn_egg;
mod spyglass;
mod standing_and_wall_block_item;
mod throwable_items;
mod throwable_potion;
mod tipped_arrow;
mod wind_charge;

mod flint_and_steel;

pub use air::AirItem;
pub use armor_stand_item::ArmorStandItem;
pub use axe::AxeItem;
pub use bed_item::BedItem;
pub use block_item::{BlockItem, DoubleHighBlockItem};
pub use boat_item::BoatItem;
pub use bonemeal::BoneMealItem;
pub use bottle::BottleItem;
pub use bow::BowItem;
pub use brush::BrushItem;
pub use bucket::BucketItem;
pub use compass::CompassItem;
pub use default::DefaultItemBehavior;
pub use dye::DyeItem;
pub use ender_eye::EnderEyeItem;
pub use ender_pearl::EnderPearlItem;
pub use firework_rocket::FireworkRocketItem;
pub use flint_and_steel::{FireChargeItem, FlintAndSteelItem};
pub use food_on_a_stick::FoodOnAStickItem;
pub use hanging_entity_item::HangingEntityItem;
pub use hoe::HoeItem;
pub use honeycomb::HoneycombItem;
pub use ink_sac::{GlowInkSacItem, InkSacItem};
pub use instrument::InstrumentItem;
pub use item_frame_item::ItemFrameItem;
pub use lead_item::{LeadItem, bind_player_mobs};
pub use mace::MaceItem;
pub use minecart_item::MinecartItem;
pub use name_tag::NameTagItem;
pub use place_on_water_block_item::PlaceOnWaterBlockItem;
pub use player_head::PlayerHeadItem;
pub use potion::PotionItem;
pub use shears::ShearsItem;
pub use shield::ShieldItem;
pub use shovel::ShovelItem;
pub use sign_item::{HangingSignItem, SignItem};
pub use spawn_egg::SpawnEggItem;
pub use spyglass::SpyglassItem;
pub use standing_and_wall_block_item::StandingAndWallBlockItem;
pub use throwable_items::{EggItem, ExperienceBottleItem, SnowballItem};
pub use throwable_potion::{LingeringPotionItem, SplashPotionItem};
pub use tipped_arrow::TippedArrowItem;
pub use wind_charge::WindChargeItem;
