package org.bukkit.event.inventory;
public enum ClickType {
 LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, WINDOW_BORDER_LEFT, WINDOW_BORDER_RIGHT,
 MIDDLE, NUMBER_KEY, DOUBLE_CLICK, DROP, CONTROL_DROP, CREATIVE,
 SWAP_OFFHAND, UNKNOWN
}
