package org.bukkit.entity;

public enum Pose { STANDING, FALL_FLYING, SLEEPING, SWIMMING, SPIN_ATTACK, CROAKING, LONG_JUMPING, DYING, DIGGING, USING_TONGUE, SITTING, ROARING, SNIFFING, EMERGING, EAT, LAYING }
